### ISSUE TITLE
Question: Why not combine the main PCB with the Thumbs PCB?

### ISSUE THREAD

**Issue by mr-september** [HID-Technologies/Skeleton-Dactyl-Mini#10]
Is there any negative effects from doing so? It seems a lot cheaper to order PCBs this way, since the main PCB has a very big unused area in the bottom right corner, so replacing that with the Thumbs PCB will only add ~7.7 mm to the combined outer dimension.

**Comment by bstiq** [comment]
Hey,

Here's a couple reasons:

- the charybdis keyboard uses the same plate, but a different thumb cluster
- it increases the total size of the pcb, so more expensive
- it makes it 2 designs in the pcb instead of just 1 - most manufacturers will charge more  because of this
- it ties together the 2 pcbs - updating one also means updating the other. Sometimes only the plate needs an update, sometimes I want to prototype on the thumb cluster, so it's nice to have them decoupled

I think this covers it, let me know if there's anything else !
